<a href="https://colab.research.google.com/github/Dcodinginsane/Data-Analysis-project/blob/main/Linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.datasets import load_diabetes

In [2]:
X,y = load_diabetes(return_X_y=True)

In [3]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [4]:
X.shape

(442, 10)

# Using Sklearn's Linear Regression

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [7]:
print(X_train.shape)
print(X_test.shape)

(353, 10)
(89, 10)


In [8]:
from sklearn.linear_model import LinearRegression

In [14]:
reg = LinearRegression().fit(X_train, X_train)

In [15]:
y_pred = reg.predict(X_test)

In [11]:
from sklearn.metrics import r2_score

In [18]:
y_test.shape , y_pred.shape

((89,), (89, 10))

In [19]:
reg.coef_

array([[ 1.00000000e+00,  3.05275366e-16, -3.70890772e-16,
         3.44871159e-17,  5.83226842e-17,  2.31760264e-16,
         2.18439046e-16, -1.71213177e-16,  2.30153661e-17,
        -2.45311596e-17],
       [-4.23522040e-16,  1.00000000e+00,  1.66533454e-16,
        -2.77555756e-16,  1.11022302e-16,  3.88578059e-16,
         1.38777878e-17,  2.77555756e-16,  1.66533454e-16,
        -1.11022302e-16],
       [-1.23521468e-16,  1.66533454e-16,  1.00000000e+00,
        -8.32667268e-17, -4.16333634e-17, -3.60822483e-16,
        -4.16333634e-17,  1.38777878e-17,  5.55111512e-17,
         2.91433544e-16],
       [-2.14355054e-16, -1.11022302e-16,  5.55111512e-17,
         1.00000000e+00, -6.38378239e-16,  7.91033905e-16,
         1.17961196e-16, -4.16333634e-17,  9.15933995e-16,
        -3.33066907e-16],
       [ 2.61390859e-16, -1.11022302e-16,  2.63677968e-16,
         3.05311332e-16,  1.00000000e+00,  4.71844785e-16,
         3.46944695e-17,  2.77555756e-16,  3.74700271e-16,
        -4.

In [20]:
reg.intercept_

array([-7.72494048e-19,  1.08420217e-18,  1.30104261e-18,  4.33680869e-19,
        9.75781955e-19,  4.33680869e-19,  0.00000000e+00,  1.73472348e-18,
        6.50521303e-19,  1.30104261e-18])

In [21]:
class MeraLR:

    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self,X_train,y_train):
        X_train = np.insert(X_train,0,1,axis=1)

        # calcuate the coeffs
        betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = betas[0]
        self.coef_ = betas[1:]

    def predict(self,X_test):
        y_pred = np.dot(X_test,self.coef_) + self.intercept_
        return y_pred

In [22]:
lr = MeraLR()

In [23]:
lr.fit(X_train,y_train)

In [24]:
X_train.shape

(353, 10)

In [25]:
np.insert(X_train,0,1,axis=1).shape

(353, 11)

In [26]:
y_pred = lr.predict(X_test)

In [27]:
r2_score(y_test,y_pred)

0.43993386615689634

In [28]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [29]:
lr.intercept_

151.88331005254165

# Multiple linear regression

In [30]:
from sklearn.datasets import make_regression
import pandas as pd
import numpy as np

import plotly.express as px
import plotly.graph_objects as go

from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [31]:
X,y = make_regression(n_samples=100, n_features=2, n_informative=2, n_targets=1, noise=50)

In [32]:
df = pd.DataFrame({'feature1':X[:,0],'feature2':X[:,1],'target':y})

In [33]:
df.shape

(100, 3)

In [34]:
df.head()

feature1  feature2     target
0 -1.176815  0.281932  17.107466
1  0.570107  1.001341 -54.937925
2  1.349714  1.446839 -72.553280
3  0.229298 -0.104051  20.513108
4  0.945925 -2.248980  42.736393

In [35]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.show()

In [36]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=3)

In [37]:
from sklearn.linear_model import LinearRegression

In [38]:
lr = LinearRegression()

In [39]:
lr.fit(X_train,y_train)

LinearRegression()

In [40]:
y_pred = lr.predict(X_test)

In [46]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("R2 score",r2_score(y_test,y_pred))

MAE 45.30898124523077
MSE 3186.501530729492
R2 score -0.09599737091931493


In [47]:
x = np.linspace(-5, 5, 10)
y = np.linspace(-5, 5, 10)
xGrid, yGrid = np.meshgrid(y, x)
final = np.vstack((xGrid.ravel().reshape(1,100),yGrid.ravel().reshape(1,100))).T

z_final = lr.predict(final).reshape(10,10)

z = z_final



In [48]:
fig = px.scatter_3d(df, x='feature1', y='feature2', z='target')

fig.add_trace(go.Surface(x = x, y = y, z =z ))

fig.show()

In [44]:
lr.coef_

array([ 0.80972234, -1.98507041])

In [45]:
lr.intercept_

-9.20914306879883